os: linux
dist: bionic
before_install:
  - sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl
  - git clone https://github.com/RPi-Distro/pi-gen.git
  - cd pi-gen
  - git checkout 2019-04-08-raspbian-stretch
addons:
  apt:
    update: true
script: pwd
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "pi-gen/*.sh"
  skip_cleanup: true
  on:
    all_branches: true
