os: linux
dist: bionic
sudo: required
addons:
  apt:
    update: true
before_install:
  - sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bash
cache:
  directories:
  - pi-gen
jobs:
  include:
    - stage: git-repo
      script:
        - rm -rf pi-gen
        - git clone https://github.com/RPi-Distro/pi-gen.git
        - cd pi-gen
        - git checkout 2019-04-08-raspbian-stretch
    - stage: debug
      script: 
        - ls
        - ls ../
    - stage: stage0
      script: 
        - set -x
        - sudo STAGE_LIST=stage0 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
    - stage: stage1
      script: sudo STAGE_LIST=stage1 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
    - stage: stage2
      script: sudo STAGE_LIST=stage2 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
    - stage: stage3
      script: sudo STAGE_LIST=stage3 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
    - stage: stage4
      script: sudo STAGE_LIST=stage4 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
    - stage: stage5
      script: sudo STAGE_LIST=stage5 IMG_NAME='Raspbian' ENABLE_SSH=1 ./pi-gen/build.sh
